### ISSUE TITLE
lambda error during function creation

### ISSUE THREAD

**Issue by adriandugan** [berlam/github-s3-deploy#1]
When creating the new blank Lambda function, what needs to be uploaded? Lambda asks for a ZIP or JAR file - what do we need to upload here? It's not clear from the README.

**Comment by berlam** [comment]
Hi Adrian,

you are right! I will extend the README. You have two options for this:

1. Download the release from the [release section](https://github.com/berlam/github-s3-deploy/releases) and [change the environment variables][1] from the AWS console.

OR

2. Build the repository by yourself from the project directory with `mvn clean package` and upload the file `target/github-s3-deploy-*.jar`. You can also [change the environment variables][1] from the AWS console.

Note:
Java isn't as good as other languages in cold start. It takes a few seconds for the application to boot (~5s). After that, the repository is initially cloned, which may take longer than 1 minute (depends on repository size). In this case you can increase the lambda timeout or upload the initial working tree by yourself on the first run. All further uploads will be checked file by file with the MD5 checksum.

Hope this helps!

[1]: http://docs.aws.amazon.com/lambda/latest/dg/env_variables.html

**Comment by adriandugan** [comment]
Thanks, got it working using option 1. Merged PRs are now flowing into my S3 bucket 👍
