### ISSUE TITLE
content-type issues upon transfer to S3

### ISSUE THREAD

**Issue by adriandugan** [berlam/github-s3-deploy#2]
When I manually upload the files (html, JS and CSS) using the S3 "upload" option (in Actions), the correct content-types are applied i.e. "text/html" for HTML files.
When the same files are deployed to S3 from github - as a result of a PR merge - their Content-Type are being set to "application/octet-stream", which means the files to not render in the browser. Have you seen this behaviour? I'm using the built JAR file in the releases tab.

**Comment by berlam** [comment]
Hi Adrian,

yes, you are right, the Content-Type was not set by the uploader. The latest release fixes this.
The Content-Type will be set, after a upload operation, which means, after the file has changed. All affected files must be changed manually or must be removed from the bucket. Afterwards you can start the sync again (you can do this without new commit when you go to the integration panel of your GitHub project, select the SNS integration and trigger a test event with the upper right button).

**Comment by adriandugan** [comment]
Yes, content-type is correct with uploads now when using v1.1 - thanks for resolving.
